# Generated by Django 5.0.2 on 2024-02-20 12:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SevenGradeTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='')),
                ('task', django_ckeditor_5.fields.CKEditor5Field()),
                ('answer', models.TextField()),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
    ]
