# Generated by Django 5.0.2 on 2024-02-21 13:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SevenGradeTasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevengradetasks',
            name='onlypicrute',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
