# Generated by Django 5.0.2 on 2024-04-02 15:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SevenGradeTasks', '0002_sevengradetasks_onlypicrute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevengradetasks',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sevengradetasks',
            name='task',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
