# Generated by Django 5.0.2 on 2024-04-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SevenGradeTasks', '0004_sevengradedirectory_alter_sevengradetasks_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sevengradedirectory',
            old_name='subtitle',
            new_name='body',
        ),
    ]
