# Generated by Django 5.0.2 on 2024-04-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SevenGradeTasks', '0005_rename_subtitle_sevengradedirectory_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sevengradedirectory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
